### ISSUE TITLE
any paper for this?

### ISSUE THREAD

**Issue by liamxg** [olli0601/hivclust#1]
@olli0601 @stephue @pmgrollemund @alexblenkinsop

**Comment by olli0601** [comment]
Hello there, sorry, there is no paper on this package -- it has been developed a long time ago and is no longer actively maintained.

**Comment by liamxg** [comment]
@olli0601 thanks for your reply.

**Comment by liamxg** [comment]
I am working on define and viz hiv cluster with network.
